In [1]:
import torch
from torch import tensor

In [2]:
# BCELoss
x = torch.Tensor([1,0.1,0.1])
y = torch.Tensor([1, 0, 0])
loss = torch.nn.BCELoss(size_average = False)
import math
x = [0.9, 0.3, 0.3]
y = [1,0,0]
l = 0
for i in range(3):
    l = l + (y[i]*math.log(x[i]) + (1 - y[i]) * math.log(1 - x[i]))
print(l)

-0.8187104035352912


In [3]:
a = Variable(torch.ones(2, 10), requires_grad = False)
x = torch.sum(a, dim = 0)
x.shape

torch.Size([10])

In [4]:
a = torch.Tensor([0,1,0])
print((a==1).nonzero())

tensor([[ 1]])


In [5]:
# nonzero()
a = torch.eye(3)
a[2,0] = 1
a = a.nonzero()

In [7]:
a = tensor([[1,2,3],[4,5,6]], dtype = torch.float)
a = torch.mean(a, 0)

In [8]:
a = torch.rand(10)
v, i = torch.topk(a, 3)

In [9]:
a = torch.rand(3,3)
b = torch.zeros(3,3)
torch.cat((a,b), 0) == torch.tensor([1,0,0], dtype = torch.float)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  1,  1],
        [ 0,  1,  1],
        [ 0,  1,  1]], dtype=torch.uint8)

In [24]:
a = tensor([[1,0,0]], dtype = torch.float)
b = torch.rand(5,3)
c = torch.cat((a, b), 0)
known = tensor([1,0,0], dtype = torch.float)
print(c * known)
print(torch.sum(c * known, 0))
torch.sum(c*known)

tensor([[ 1.0000,  0.0000,  0.0000],
        [ 0.7018,  0.0000,  0.0000],
        [ 0.2394,  0.0000,  0.0000],
        [ 0.2163,  0.0000,  0.0000],
        [ 0.9227,  0.0000,  0.0000],
        [ 0.1341,  0.0000,  0.0000]])
tensor([ 3.2143,  0.0000,  0.0000])


tensor(3.2143)

In [28]:
a = torch.tensor([[1,2,3]])
b = torch.tensor([[3,4,5]])
c = torch.cat((a, b), 0)

tensor([[ 1,  2,  3],
        [ 3,  4,  5]])
tensor([[  3,  15,   5]])
tensor([[ 1,  2,  3],
        [ 3,  4,  5]])


In [17]:
a = torch.tensor([1, 2, 3])

In [19]:
int(a)

ValueError: only one element tensors can be converted to Python scalars