In [1]:
import numpy as np

In [2]:
a = np.zeros((5,3))
print(a)
a[1,1] = 1
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
a = np.arange(10)
b = np.arange(10)
idx = np.random.choice(a, 10, replace = False)
x = a[idx]
y = b[idx]
x == y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [18]:
label = np.random.randn(5,10)
image = np.random.randn(5,3,24,24)
idx = np.random.choice(np.arange(label.shape[0]), 3, replace = False)

In [46]:
a = np.random.randn(3,3)

a_val = a[-2:,]

In [47]:
a_val.shape

(2, 3)