In [1]:
import torch
from torch import tensor

In [2]:
# BCELoss
x = torch.Tensor([1,0.1,0.1])
y = torch.Tensor([1, 0, 0])
loss = torch.nn.BCELoss(size_average = False)
import math
x = [0.9, 0.3, 0.3]
y = [1,0,0]
l = 0
for i in range(3):
    l = l + (y[i]*math.log(x[i]) + (1 - y[i]) * math.log(1 - x[i]))
print(l)

-0.8187104035352912


In [3]:
a = Variable(torch.ones(2, 10), requires_grad = False)
x = torch.sum(a, dim = 0)
x.shape

torch.Size([10])

In [4]:
a = torch.Tensor([0,1,0])
print((a==1).nonzero())

tensor([[ 1]])


In [5]:
# nonzero()
a = torch.eye(3)
a[2,0] = 1
a = a.nonzero()

In [7]:
a = tensor([[1,2,3],[4,5,6]], dtype = torch.float)
a = torch.mean(a, 0)

In [8]:
a = torch.rand(10)
v, i = torch.topk(a, 3)

In [9]:
a = torch.rand(3,3)
b = torch.zeros(3,3)
torch.cat((a,b), 0) == torch.tensor([1,0,0], dtype = torch.float)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  1,  1],
        [ 0,  1,  1],
        [ 0,  1,  1]], dtype=torch.uint8)

In [24]:
a = tensor([[1,0,0]], dtype = torch.float)
b = torch.rand(5,3)
c = torch.cat((a, b), 0)
known = tensor([1,0,0], dtype = torch.float)
print(c * known)
print(torch.sum(c * known, 0))
torch.sum(c*known)

tensor([[ 1.0000,  0.0000,  0.0000],
        [ 0.7018,  0.0000,  0.0000],
        [ 0.2394,  0.0000,  0.0000],
        [ 0.2163,  0.0000,  0.0000],
        [ 0.9227,  0.0000,  0.0000],
        [ 0.1341,  0.0000,  0.0000]])
tensor([ 3.2143,  0.0000,  0.0000])


tensor(3.2143)

In [28]:
a = torch.tensor([[1,2,3]])
b = torch.tensor([[3,4,5]])
c = torch.cat((a, b), 0)

tensor([[ 1,  2,  3],
        [ 3,  4,  5]])
tensor([[  3,  15,   5]])
tensor([[ 1,  2,  3],
        [ 3,  4,  5]])


In [27]:
import torchvision
resnet18 = torchvision.models.resnet18(pretrained = True)
z = torch.zeros(10, 1000).cuda()
f = resnet18.cuda()
for i in range(2):
    x = torch.rand(1,3,224,224).cuda()
    print(torch.cuda.memory_allocated(), 'hello')
    y = f(x)
    y = y.view(1, -1).detach()
    z[i] = y

95214080 hello
95214080 hello


In [31]:
x = torch.tensor([1])
y = torch.tensor([2])
f = x > y
if f:
    print('he')

In [38]:
def choose_top(nb_proto,feature_mem, image_mem, image_orig_mem, class_mean):
        assert feature_mem.shape[0] == image_mem.shape[0]
        visited = torch.zeros(feature_mem.shape[0], dtype = torch.uint8)
        tot = torch.zeros(feature_mem.shape[1])
        protoset_index = []
        for i in range(nb_proto):
            distance = torch.tensor(float('inf'))
            p = -1
            for item in range(feature_mem.shape[0]):
                if(visited[item] != 0):
                    avg = (tot + feature_mem[i]) / (i + 1)
                    distance_temp = torch.norm(class_mean - avg)
                    if(distance_temp < distance):
                        p = i
            protoset_index.append(p)
        index = torch.tensor(protoset_index)
        protoset = image_mem[index].clone()
        protoset_orig = image_orig_mem[index].clone()
        return [protoset, protoset_orig, class_mean]

In [39]:
feature_mem = torch.rand(50,512)
image_mem = torch.randn(50, 3, 224, 224)
image_orig_mem = torch.randn(50, 3, 32, 32)
class_mean = torch.rand(512)
x = choose_top(3, feature_mem, image_mem, image_orig_mem, class_mean)

In [8]:
a = torch.rand((3, 3))

In [9]:
a.dtype

torch.float32

In [10]:
a = a.double()

In [11]:
a.dtype

torch.float64

In [12]:
torch.mean(a)

tensor(0.5507, dtype=torch.float64)