In [24]:
import numpy as np
import pickle

In [2]:
a = np.zeros((5,3))
print(a)
a[1,1] = 1
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
a = np.arange(10)
b = np.arange(10)
idx = np.random.choice(a, 10, replace = False)
x = a[idx]
y = b[idx]
x == y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [4]:
label = np.random.randn(5,10)
image = np.random.randn(5,3,24,24)
idx = np.random.choice(np.arange(label.shape[0]), 3, replace = False)

In [19]:
a = np.empty((2,3))
print(a)
a[:] = np.nan
a

[[2.46151512e-312 5.30276956e+180 5.05117710e-038]
 [6.97666940e-076 3.45618042e-086 3.35709878e-143]]


array([[nan, nan, nan],
       [nan, nan, nan]])

In [14]:
a = np.ones((3,3)) * np.array([1,0,0])
b = np.array([[1,2,3]])
np.concatenate((a,b), axis = 0)

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 2., 3.]])

In [23]:
label = np.zeros(10)
label[4] = 1
print(label)
proto_labels = np.ones((20, 10)) * label

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [32]:
d = pickle.load(open('/mnt/e/ilex/protoset0', 'rb'))
a = d[4]